<?php
    class Entidad{

        public $codigo;
        public $idTipoDoc;
        public $numDoc;
        public $apePaterno;
        public $apeMaterno;
        public $nombres;
        public $razonSocial;
        public $correo;
        public $telefono1;
        public $telefono2;
        public $fecEliminado;
        public $observacion;
        public $flagSocio;
        public $flagCriador;
        public $flagPropietario;
        public $flagSituacion;
        public $idPropietario;
        public $idDpto;
        public $lugarCria;
        public $prefijo;
        public $login;
        public $password;
    }

?>